# Generated by Django 2.2 on 2021-12-14 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type_question', models.CharField(choices=[('text_field', 'Ответ текстом'), ('radio', 'Один вариант'), ('check_boxes', 'Выбор нескольких вариантов')], max_length=20, verbose_name='Тип вопроса')),
                ('poll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.Poll')),
            ],
        ),
    ]
